### ISSUE TITLE
Lot's of sockets in CLOSE-WAIT

### ISSUE THREAD

**Issue by ashangit** [criteo/garmadon#17]
On few of our servers during roll restart of forwarder service due to release bump we can observe bad sockets behaviour with lots of CLOSE-WAIT sockets from container to forwarder
```
> ss -np|grep 33000|grep CLOSE-WAIT|wc -l
26358

Netid  State      Recv-Q Send-Q Local Address:Port           Peer Address:Port      
tcp    CLOSE-WAIT 0      0      127.0.0.1:33068              127.0.0.1:33000               users:(("java",pid=46695,fd=4494))
tcp    CLOSE-WAIT 0      0      127.0.0.1:35035              127.0.0.1:33000               users:(("java",pid=46695,fd=26321))
```

**Comment by Willymontaz** [comment]
Reopened until no more processed containing such agent runs on the cluster / gateways

**Comment by ashangit** [comment]
The patch solved this issue
If we want to follow state of the patch on our infra we should open a request in our internal repo.
Here we should only report feature, bug... and close when code is merged

**Comment by Willymontaz** [comment]
Yes, right
