### ISSUE TITLE
garmadon at kerberosed kafka

### ISSUE THREAD

**Issue by kockockockoc** [criteo/garmadon#99]
Hello!
I try to setup: garmadon-forwarder -> [kerberosed kafka] -> garmadon-readers-elasticsearch

* garmadon-forwarder -> [kerberosed kafka] - that works fine
* [kerberosed kafka] -> garmadon-readers-elasticsearch - can't pass SASL params to reader: sasl.kerberos.service.name, security.protocol, sasl.jaas.config

How to do it?

**Comment by ashangit** [comment]
This is not possible currently from readers currently.
On forwarder side we well load kafka properties on the server.properties file but did not duplicate such mechanism on readers.
Will look at providing such a thing soon

**Comment by kockockockoc** [comment]
looking forward to it! cauz I can produce to kafka and can't consume it.
